# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from codee import simpleNetworkSEIQRModel
# from PyQt5.QtGui import QMovie
from PyQt5.QtMultimedia import *
from PyQt5.QtMultimediaWidgets import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QIcon, QPixmap
import time
import sys


class Ui_MainWindow(object):
    def run_simulation(self):
        # beta = float(self.lineEdit_Beta.text())  # transmission rate
        # epsilon = float(self.lineEdit_Epsilon.text()) # the latent period    6, 7, 8, 9, 10
        # rho = float(self.lineEdit_Rho.text())   # I -> Q rate          1/....
        # omega = float(self.lineEdit_Omega.text())  # I -> R rate, 16, 18, 20, 10, 12, 14
        # kappa = float(self.lineEdit_Kappa.text())   # I -> D rate
        # tau =  float(self.lineEdit_Tau.text())   # Q -> R rate
        # sigma = float(self.lineEdit_Sigma.text())  # Q -> D rate  
        # #print(sigma)
        # S = int(self.lineEdit_Susceptible.text())
        # E = int(self.lineEdit_Infected.text())
        # #print ("Clicked")
        # I = 0
        # Q = 0
        # R = 0
        # simulation_code = simpleNetworkSEIQRModel(beta, epsilon, rho, omega, kappa, tau, sigma, S, E, I, Q, R)
        # self.end = simulation_code.mainn(beta, epsilon, rho, omega, kappa, tau, sigma, S, E, I, Q, R)
        # if self.end == 100:
            # self.movie.start()
            # time.sleep(5)
        self.mediaPlayer.play()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 1282, 562))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(255, 255, 255);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(90, 249, 111);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(90, 249, 111);\n"
"}\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(90, 249, 111);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(90, 249, 111);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1268, 1018))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_Inputs = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Inputs.sizePolicy().hasHeightForWidth())
        self.widget_Inputs.setSizePolicy(sizePolicy)
        self.widget_Inputs.setMaximumSize(QtCore.QSize(1300, 100))
        self.widget_Inputs.setObjectName("widget_Inputs")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_Inputs)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.lineEdit_Susceptible = QtWidgets.QLineEdit(self.widget_Inputs)
        self.lineEdit_Susceptible.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Susceptible.setFont(font)
        self.lineEdit_Susceptible.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Susceptible.setText("")
        self.lineEdit_Susceptible.setObjectName("lineEdit_Susceptible")
        self.gridLayout.addWidget(self.lineEdit_Susceptible, 0, 0, 1, 1)

        self.lineEdit_Infected = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Infected.setFont(font)
        self.lineEdit_Infected.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Infected.setObjectName("lineEdit_Infected")
        self.gridLayout.addWidget(self.lineEdit_Infected, 0, 1, 1, 1)

        self.lineEdit_Beta = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Beta.setFont(font)
        self.lineEdit_Beta.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Beta.setObjectName("lineEdit_Beta")
        self.gridLayout.addWidget(self.lineEdit_Beta, 0, 2, 1, 1)

        self.lineEdit_Epsilon = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Epsilon.setFont(font)
        self.lineEdit_Epsilon.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Epsilon.setObjectName("lineEdit_Epsilon")
        self.gridLayout.addWidget(self.lineEdit_Epsilon, 0, 3, 1, 1)

        self.lineEdit_Rho = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Rho.setFont(font)
        self.lineEdit_Rho.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Rho.setObjectName("lineEdit_Rho")
        self.gridLayout.addWidget(self.lineEdit_Rho, 0, 4, 1, 1)

        self.lineEdit_Omega = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Omega.setFont(font)
        self.lineEdit_Omega.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Omega.setObjectName("lineEdit_Omega")
        self.gridLayout.addWidget(self.lineEdit_Omega, 2, 0, 1, 1)

        self.lineEdit_Kappa = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Kappa.setFont(font)
        self.lineEdit_Kappa.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Kappa.setObjectName("lineEdit_Kappa")
        self.gridLayout.addWidget(self.lineEdit_Kappa, 2, 1, 1, 1)

        self.lineEdit_Tau = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Tau.setFont(font)
        self.lineEdit_Tau.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Tau.setObjectName("lineEdit_Tau")
        self.gridLayout.addWidget(self.lineEdit_Tau, 2, 2, 1, 1)

        self.lineEdit_Sigma = QtWidgets.QLineEdit(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Sigma.setFont(font)
        self.lineEdit_Sigma.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"")
        self.lineEdit_Sigma.setObjectName("lineEdit_Sigma")
        self.gridLayout.addWidget(self.lineEdit_Sigma, 2, 3, 1, 1)

        self.pushButton_Run = QtWidgets.QPushButton(self.widget_Inputs)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"\n"
"")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.gridLayout.addWidget(self.pushButton_Run, 2, 4, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_Inputs)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_animation = QtWidgets.QFrame(self.frame)
        self.frame_animation.setMaximumSize(QtCore.QSize(611, 400))
        self.frame_animation.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    border-radius: 50px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"}\n"
"")
        self.frame_animation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_animation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_animation.setObjectName("frame_animation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_animation)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)
        self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile('Animation.mp4')))

        # Set widget
        self.videoWidget = QVideoWidget(self.frame_animation)
        self.videoWidget.setGeometry(QtCore.QRect(0, 0, 611, 400))
        self.videoWidget.setAspectRatioMode(Qt.KeepAspectRatioByExpanding)
#         self.videoWidget.setStyleSheet("QVideoWidget{\n"
# "   background-color: red;\n"
# "}\n"
# "")
        # self.setCentralWidget(self.videoWidget)
        self.mediaPlayer.setVideoOutput(self.videoWidget)
        self.mediaPlayer.stateChanged.connect(self.mediastate_changed)
        self.mediaPlayer.positionChanged.connect(self.position_changed)
        self.mediaPlayer.durationChanged.connect(self.duration_changed)
        #self.label_rem1 = QtWidgets.QLabel(self.frame_animation)
        #self.label_rem1.setMaximumSize(QtCore.QSize(611, 400))
        #self.label_rem1.setObjectName("label_rem1")
        self.gridLayout_4.addWidget(self.videoWidget, 0, 0, 1, 4)

        self.pushButton_play = QtWidgets.QPushButton(self.frame_animation)
        self.pushButton_play.setIcon(QIcon(QPixmap("play.png")))
        self.pushButton_play.clicked.connect(self.play_video)
        self.pushButton_play.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_play.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    icon-size: 30px;\n"
"}\n"
"\n"
"")
        self.pushButton_play.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton_play, 1, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_animation)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(350, 30))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.sliderMoved.connect(self.set_position)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #31db54, stop: 1 #8cff99);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #8cff99, stop: 1 #10cc46);\n"
"border: 1px solid #6bff7d;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #31db54;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.gridLayout_4.addWidget(self.horizontalSlider, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_animation, 0, 0, 1, 1)
        self.widget_All_plots = QtWidgets.QWidget(self.frame)
        self.widget_All_plots.setMaximumSize(QtCore.QSize(611, 400))
        self.widget_All_plots.setStyleSheet("QWidget{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    border-radius: 50px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_All_plots.setObjectName("widget_All_plots")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_All_plots)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_all_plots = QtWidgets.QLabel(self.widget_All_plots)
        self.label_all_plots.setStyleSheet("border: none;")
        self.label_all_plots.setText("")
        self.label_all_plots.setObjectName("label_all_plots")
        self.verticalLayout_5.addWidget(self.label_all_plots)
        self.gridLayout_2.addWidget(self.widget_All_plots, 0, 1, 1, 1)
        self.widget_Table = QtWidgets.QWidget(self.frame)
        self.widget_Table.setStyleSheet("QWidget{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    border-radius: 50px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_Table.setObjectName("widget_Table")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_Table)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_result = QtWidgets.QLabel(self.widget_Table)
        self.label_result.setMaximumSize(QtCore.QSize(611, 400))
        self.label_result.setStyleSheet("border: none;")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_4.addWidget(self.label_result)
        self.gridLayout_2.addWidget(self.widget_Table, 1, 1, 1, 1)
        self.widget_Two_plots = QtWidgets.QWidget(self.frame)
        self.widget_Two_plots.setMaximumSize(QtCore.QSize(611, 400))
        self.widget_Two_plots.setStyleSheet("QWidget{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    border-radius: 50px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_Two_plots.setObjectName("widget_Two_plots")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_Two_plots)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_rem2 = QtWidgets.QLabel(self.widget_Two_plots)
        self.label_rem2.setObjectName("label_rem2")
        self.gridLayout_5.addWidget(self.label_rem2, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(237, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_open_data = QtWidgets.QPushButton(self.widget_Two_plots)
        self.pushButton_open_data.setMaximumSize(QtCore.QSize(102, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open_data.setFont(font)
        self.pushButton_open_data.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(90, 249, 111);\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    width: 180px;\n"
"}\n"
"\n"
"")
        self.pushButton_open_data.setObjectName("pushButton_open_data")
        self.gridLayout_5.addWidget(self.pushButton_open_data, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget_Two_plots, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_Epsilon.setPlaceholderText(_translate("MainWindow", "Epsilon (latent period)"))
        self.lineEdit_Sigma.setPlaceholderText(_translate("MainWindow", "Sigma (Q -> D rate)"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run simulation"))
        self.lineEdit_Susceptible.setPlaceholderText(_translate("MainWindow", "Susceptible"))
        self.lineEdit_Tau.setPlaceholderText(_translate("MainWindow", "Tau (Q -> R rate)"))
        self.lineEdit_Infected.setPlaceholderText(_translate("MainWindow", "Infected"))
        self.lineEdit_Omega.setPlaceholderText(_translate("MainWindow", "Omega (I -> R rate)"))
        self.lineEdit_Beta.setPlaceholderText(_translate("MainWindow", "Beta (transmission rate)"))
        self.lineEdit_Kappa.setPlaceholderText(_translate("MainWindow", "Kappa (I -> D rate)"))
        self.lineEdit_Rho.setPlaceholderText(_translate("MainWindow", "Rho (I -> Q rate)"))
        #self.label_rem1.setText(_translate("MainWindow", "TextLabel"))
        # self.pushButton_play.setText(_translate("MainWindow", "PushButton"))
        self.label_rem2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_open_data.setText(_translate("MainWindow", "Open Data"))
        self.pushButton_Run.clicked.connect(self.run_simulation)

    def play_video(self):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.mediaPlayer.pause()
            print("media pause")
        else:
            self.mediaPlayer.play()    
            print("media play")

    def mediastate_changed(self, state):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.pushButton_play.setIcon(QIcon(QPixmap("pause.png")))
            print("icon pause")
        else:
            self.pushButton_play.setIcon(QIcon(QPixmap("play.png")))
            print("icon play")

    def position_changed(self, position):
        self.horizontalSlider.setValue(position)


    def duration_changed(self, duration):
        self.horizontalSlider.setRange(0, duration)


    def set_position(self, position):
        self.mediaPlayer.setPosition(position)        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
